/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffddb8',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#ffd4a4',
        'on-surface': '#131b2e',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#4edea3',
        'secondary-container': '#6cf8bb',
        'on-primary-fixed': '#0f0069',
        'surface-container': '#eaedff',
        'on-surface-variant': '#464555',
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#3323cc',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#005236',
        'secondary-fixed': '#6ffbbe',
        surface: '#faf8ff',
        'primary-fixed-dim': '#c3c0ff',
        outline: '#777587',
        'primary-fixed': '#e2dfff',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-dim': '#d2d9f4',
        'surface-tint': '#4d44e3',
        'inverse-on-surface': '#eef0ff',
        'on-tertiary-fixed': '#2a1700',
        background: '#faf8ff',
        'inverse-primary': '#c3c0ff',
        'outline-variant': '#c7c4d8',
        'on-secondary-container': '#00714d',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#dae2fd',
        'on-primary-container': '#dad7ff',
        'surface-container-low': '#f2f3ff',
        'inverse-surface': '#283044',
        'surface-bright': '#faf8ff',
        secondary: '#006c49',
        'on-secondary-fixed': '#002113',
        tertiary: '#684000',
        'on-background': '#131b2e',
        'tertiary-container': '#885500',
        'surface-container-high': '#e2e7ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        gutter: '24px',
        sm: '8px',
        'container-max': '1440px',
        '2xl': '48px',
        base: '4px',
        xs: '4px',
        md: '16px',
        xl: '32px',
        '3xl': '64px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-metrics': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-metrics': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

